framework:
    secret: '%env(APP_SECRET)%'
    
    # Enables session support
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    # PHP error handling
    php_errors:
        log: true

    # Asset handling
    assets: ~

    # HTTP cache

    # Cache configuration
    cache:
        # app: cache.adapter.filesystem
